{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "66557e7c-6c06-4632-853b-4853df38d06e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "591a31e6-9d0a-4b60-98da-5c1ec5d82ee8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "#os.environ[\"CUDA_DEVICE_ORDER\"] = \"PCI_BUS_ID\"   # see issue #152\n",
    "#os.environ[\"CUDA_VISIBLE_DEVICES\"] = \"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "a3ab3900-3c7d-4f2d-b869-47675d4f51f9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Default GPU Name: [name: \"/device:CPU:0\"\n",
      "device_type: \"CPU\"\n",
      "memory_limit: 268435456\n",
      "locality {\n",
      "}\n",
      "incarnation: 125867206689675930\n",
      "xla_global_id: -1\n",
      ", name: \"/device:GPU:0\"\n",
      "device_type: \"GPU\"\n",
      "memory_limit: 4226416640\n",
      "locality {\n",
      "  bus_id: 1\n",
      "  links {\n",
      "  }\n",
      "}\n",
      "incarnation: 2545836500570839219\n",
      "physical_device_desc: \"device: 0, name: NVIDIA GeForce GTX 1660, pci bus id: 0000:07:00.0, compute capability: 7.5\"\n",
      "xla_global_id: 416903419\n",
      "]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "I0000 00:00:1736020143.675385    6708 gpu_device.cc:2022] Created device /device:GPU:0 with 4030 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1660, pci bus id: 0000:07:00.0, compute capability: 7.5\n",
      "I0000 00:00:1736020143.677085    6708 gpu_device.cc:2022] Created device /device:GPU:0 with 4030 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1660, pci bus id: 0000:07:00.0, compute capability: 7.5\n"
     ]
    }
   ],
   "source": [
    "import tensorflow as tf\n",
    "from tensorflow.python.client import device_lib\n",
    "from tensorflow import keras\n",
    "\n",
    "if tf.test.gpu_device_name():\n",
    "    print('Default GPU Name: {}'.format(device_lib.list_local_devices()))\n",
    "else:\n",
    "    print(\"Please install GPU version of TF\")\n",
    "    print('Acesse o menu Edit > Notebook Settings')\n",
    "    print('Escolha a opção \"Hardware Accelerator: GPU\"')\n",
    "    print('Importe novamente as bibliotecas e execute o código novamente')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "1ea6a0b3-f001-40bb-954e-6a6e01ed3b03",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[CudaDevice(id=0)]\n"
     ]
    }
   ],
   "source": [
    "from jax import jit, random, config\n",
    "config.update('jax_enable_x64', True)\n",
    "import jax\n",
    "import jax.numpy as jnp\n",
    "print(jax.devices())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "de4ec215-2e67-4b53-ae2a-ec6051394dd8",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "#pip install tensorflow[and-cuda]\n",
    "#pip install jax[cuda]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "e2d80715-81d0-4bba-aa77-7d9c7ded5541",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting git+file:/home/falreis/Me/doutorado/clrs/\n",
      "  Cloning file:///home/falreis/Me/doutorado/clrs/ to /tmp/pip-req-build-9yi6o5g3\n",
      "  Running command git clone --filter=blob:none --quiet file:///home/falreis/Me/doutorado/clrs/ /tmp/pip-req-build-9yi6o5g3\n",
      "  warning: filtering not recognized by server, ignoring\n",
      "  Resolved file:///home/falreis/Me/doutorado/clrs/ to commit 5f51c49832b1b60ba5924ac107e6e643ef9482b9\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: absl-py>=2.1.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from dm-clrs==2.0.1) (2.1.0)\n",
      "Requirement already satisfied: attrs>=24.2.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from dm-clrs==2.0.1) (24.3.0)\n",
      "Requirement already satisfied: chex>=0.1.86 in /home/falreis/anaconda3/lib/python3.12/site-packages (from dm-clrs==2.0.1) (0.1.88)\n",
      "Requirement already satisfied: dm-haiku>=0.0.12 in /home/falreis/anaconda3/lib/python3.12/site-packages (from dm-clrs==2.0.1) (0.0.13)\n",
      "Requirement already satisfied: jax>=0.4.31 in /home/falreis/anaconda3/lib/python3.12/site-packages (from dm-clrs==2.0.1) (0.4.38)\n",
      "Requirement already satisfied: jaxlib>=0.4.31 in /home/falreis/anaconda3/lib/python3.12/site-packages (from dm-clrs==2.0.1) (0.4.38)\n",
      "Requirement already satisfied: ml_collections>=0.1.1 in /home/falreis/anaconda3/lib/python3.12/site-packages (from dm-clrs==2.0.1) (1.0.0)\n",
      "Requirement already satisfied: numpy>=1.26.4 in /home/falreis/anaconda3/lib/python3.12/site-packages (from dm-clrs==2.0.1) (2.0.2)\n",
      "Requirement already satisfied: opt-einsum>=3.3.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from dm-clrs==2.0.1) (3.4.0)\n",
      "Requirement already satisfied: optax>=0.2.3 in /home/falreis/anaconda3/lib/python3.12/site-packages (from dm-clrs==2.0.1) (0.2.4)\n",
      "Requirement already satisfied: six>=1.16.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from dm-clrs==2.0.1) (1.17.0)\n",
      "Requirement already satisfied: tensorflow>=2.17.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from dm-clrs==2.0.1) (2.18.0)\n",
      "Requirement already satisfied: tfds-nightly>=4.9.6.dev202409060044 in /home/falreis/anaconda3/lib/python3.12/site-packages (from dm-clrs==2.0.1) (4.9.7.dev202501040044)\n",
      "Requirement already satisfied: toolz>=0.12.1 in /home/falreis/anaconda3/lib/python3.12/site-packages (from dm-clrs==2.0.1) (1.0.0)\n",
      "Requirement already satisfied: typing_extensions>=4.2.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from chex>=0.1.86->dm-clrs==2.0.1) (4.12.2)\n",
      "Requirement already satisfied: setuptools in /home/falreis/anaconda3/lib/python3.12/site-packages (from chex>=0.1.86->dm-clrs==2.0.1) (75.6.0)\n",
      "Requirement already satisfied: jmp>=0.0.2 in /home/falreis/anaconda3/lib/python3.12/site-packages (from dm-haiku>=0.0.12->dm-clrs==2.0.1) (0.0.4)\n",
      "Requirement already satisfied: tabulate>=0.8.9 in /home/falreis/anaconda3/lib/python3.12/site-packages (from dm-haiku>=0.0.12->dm-clrs==2.0.1) (0.9.0)\n",
      "Requirement already satisfied: ml_dtypes>=0.4.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from jax>=0.4.31->dm-clrs==2.0.1) (0.4.1)\n",
      "Requirement already satisfied: scipy>=1.10 in /home/falreis/anaconda3/lib/python3.12/site-packages (from jax>=0.4.31->dm-clrs==2.0.1) (1.15.0)\n",
      "Requirement already satisfied: PyYAML in /home/falreis/anaconda3/lib/python3.12/site-packages (from ml_collections>=0.1.1->dm-clrs==2.0.1) (6.0.2)\n",
      "Requirement already satisfied: etils[epy] in /home/falreis/anaconda3/lib/python3.12/site-packages (from optax>=0.2.3->dm-clrs==2.0.1) (1.11.0)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from tensorflow>=2.17.0->dm-clrs==2.0.1) (1.6.3)\n",
      "Requirement already satisfied: flatbuffers>=24.3.25 in /home/falreis/anaconda3/lib/python3.12/site-packages (from tensorflow>=2.17.0->dm-clrs==2.0.1) (24.12.23)\n",
      "Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /home/falreis/anaconda3/lib/python3.12/site-packages (from tensorflow>=2.17.0->dm-clrs==2.0.1) (0.6.0)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in /home/falreis/anaconda3/lib/python3.12/site-packages (from tensorflow>=2.17.0->dm-clrs==2.0.1) (0.2.0)\n",
      "Requirement already satisfied: libclang>=13.0.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from tensorflow>=2.17.0->dm-clrs==2.0.1) (18.1.1)\n",
      "Requirement already satisfied: packaging in /home/falreis/anaconda3/lib/python3.12/site-packages (from tensorflow>=2.17.0->dm-clrs==2.0.1) (24.2)\n",
      "Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /home/falreis/anaconda3/lib/python3.12/site-packages (from tensorflow>=2.17.0->dm-clrs==2.0.1) (5.29.2)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from tensorflow>=2.17.0->dm-clrs==2.0.1) (2.32.3)\n",
      "Requirement already satisfied: termcolor>=1.1.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from tensorflow>=2.17.0->dm-clrs==2.0.1) (2.5.0)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from tensorflow>=2.17.0->dm-clrs==2.0.1) (1.17.0)\n",
      "Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/falreis/anaconda3/lib/python3.12/site-packages (from tensorflow>=2.17.0->dm-clrs==2.0.1) (1.68.1)\n",
      "Requirement already satisfied: tensorboard<2.19,>=2.18 in /home/falreis/anaconda3/lib/python3.12/site-packages (from tensorflow>=2.17.0->dm-clrs==2.0.1) (2.18.0)\n",
      "Requirement already satisfied: keras>=3.5.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from tensorflow>=2.17.0->dm-clrs==2.0.1) (3.7.0)\n",
      "Requirement already satisfied: h5py>=3.11.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from tensorflow>=2.17.0->dm-clrs==2.0.1) (3.12.1)\n",
      "Requirement already satisfied: array_record>=0.5.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from tfds-nightly>=4.9.6.dev202409060044->dm-clrs==2.0.1) (0.6.0)\n",
      "Requirement already satisfied: dm-tree in /home/falreis/anaconda3/lib/python3.12/site-packages (from tfds-nightly>=4.9.6.dev202409060044->dm-clrs==2.0.1) (0.1.8)\n",
      "Requirement already satisfied: immutabledict in /home/falreis/anaconda3/lib/python3.12/site-packages (from tfds-nightly>=4.9.6.dev202409060044->dm-clrs==2.0.1) (4.2.1)\n",
      "Requirement already satisfied: promise in /home/falreis/anaconda3/lib/python3.12/site-packages (from tfds-nightly>=4.9.6.dev202409060044->dm-clrs==2.0.1) (2.3)\n",
      "Requirement already satisfied: psutil in /home/falreis/anaconda3/lib/python3.12/site-packages (from tfds-nightly>=4.9.6.dev202409060044->dm-clrs==2.0.1) (6.1.1)\n",
      "Requirement already satisfied: pyarrow in /home/falreis/anaconda3/lib/python3.12/site-packages (from tfds-nightly>=4.9.6.dev202409060044->dm-clrs==2.0.1) (18.1.0)\n",
      "Requirement already satisfied: simple_parsing in /home/falreis/anaconda3/lib/python3.12/site-packages (from tfds-nightly>=4.9.6.dev202409060044->dm-clrs==2.0.1) (0.1.6)\n",
      "Requirement already satisfied: tensorflow-metadata in /home/falreis/anaconda3/lib/python3.12/site-packages (from tfds-nightly>=4.9.6.dev202409060044->dm-clrs==2.0.1) (1.16.1)\n",
      "Requirement already satisfied: toml in /home/falreis/anaconda3/lib/python3.12/site-packages (from tfds-nightly>=4.9.6.dev202409060044->dm-clrs==2.0.1) (0.10.2)\n",
      "Requirement already satisfied: tqdm in /home/falreis/anaconda3/lib/python3.12/site-packages (from tfds-nightly>=4.9.6.dev202409060044->dm-clrs==2.0.1) (4.67.1)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from astunparse>=1.6.0->tensorflow>=2.17.0->dm-clrs==2.0.1) (0.45.1)\n",
      "Requirement already satisfied: fsspec in /home/falreis/anaconda3/lib/python3.12/site-packages (from etils[edc,enp,epath,epy,etree]>=1.9.1; python_version >= \"3.11\"->tfds-nightly>=4.9.6.dev202409060044->dm-clrs==2.0.1) (2024.12.0)\n",
      "Requirement already satisfied: importlib_resources in /home/falreis/anaconda3/lib/python3.12/site-packages (from etils[edc,enp,epath,epy,etree]>=1.9.1; python_version >= \"3.11\"->tfds-nightly>=4.9.6.dev202409060044->dm-clrs==2.0.1) (6.5.2)\n",
      "Requirement already satisfied: zipp in /home/falreis/anaconda3/lib/python3.12/site-packages (from etils[edc,enp,epath,epy,etree]>=1.9.1; python_version >= \"3.11\"->tfds-nightly>=4.9.6.dev202409060044->dm-clrs==2.0.1) (3.21.0)\n",
      "Requirement already satisfied: rich in /home/falreis/anaconda3/lib/python3.12/site-packages (from keras>=3.5.0->tensorflow>=2.17.0->dm-clrs==2.0.1) (13.9.4)\n",
      "Requirement already satisfied: namex in /home/falreis/anaconda3/lib/python3.12/site-packages (from keras>=3.5.0->tensorflow>=2.17.0->dm-clrs==2.0.1) (0.0.8)\n",
      "Requirement already satisfied: optree in /home/falreis/anaconda3/lib/python3.12/site-packages (from keras>=3.5.0->tensorflow>=2.17.0->dm-clrs==2.0.1) (0.13.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/falreis/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow>=2.17.0->dm-clrs==2.0.1) (3.4.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /home/falreis/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow>=2.17.0->dm-clrs==2.0.1) (3.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/falreis/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow>=2.17.0->dm-clrs==2.0.1) (2.3.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /home/falreis/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow>=2.17.0->dm-clrs==2.0.1) (2024.12.14)\n",
      "Requirement already satisfied: markdown>=2.6.8 in /home/falreis/anaconda3/lib/python3.12/site-packages (from tensorboard<2.19,>=2.18->tensorflow>=2.17.0->dm-clrs==2.0.1) (3.7)\n",
      "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from tensorboard<2.19,>=2.18->tensorflow>=2.17.0->dm-clrs==2.0.1) (0.7.2)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in /home/falreis/anaconda3/lib/python3.12/site-packages (from tensorboard<2.19,>=2.18->tensorflow>=2.17.0->dm-clrs==2.0.1) (3.1.3)\n",
      "Requirement already satisfied: docstring-parser<1.0,>=0.15 in /home/falreis/anaconda3/lib/python3.12/site-packages (from simple_parsing->tfds-nightly>=4.9.6.dev202409060044->dm-clrs==2.0.1) (0.16)\n",
      "Requirement already satisfied: googleapis-common-protos<2,>=1.56.4 in /home/falreis/anaconda3/lib/python3.12/site-packages (from tensorflow-metadata->tfds-nightly>=4.9.6.dev202409060044->dm-clrs==2.0.1) (1.66.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in /home/falreis/anaconda3/lib/python3.12/site-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow>=2.17.0->dm-clrs==2.0.1) (3.0.2)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from rich->keras>=3.5.0->tensorflow>=2.17.0->dm-clrs==2.0.1) (3.0.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/falreis/anaconda3/lib/python3.12/site-packages (from rich->keras>=3.5.0->tensorflow>=2.17.0->dm-clrs==2.0.1) (2.18.0)\n",
      "Requirement already satisfied: mdurl~=0.1 in /home/falreis/anaconda3/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow>=2.17.0->dm-clrs==2.0.1) (0.1.2)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install git+file:///home/falreis/Me/doutorado/clrs/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "b61cd300-0b5d-4712-bb36-df18b3bb7ef8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/home/falreis/Me/doutorado/clrs/clrs\n"
     ]
    }
   ],
   "source": [
    "cd clrs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "76c03815-1027-4f9a-8031-5298a3ff9a09",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2025-01-04 16:48:32.800231: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
      "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
      "E0000 00:00:1736020112.818257    7345 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
      "E0000 00:00:1736020112.823673    7345 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/home/falreis/Me/doutorado/clrs/clrs/examples/run.py\", line 26, in <module>\n",
      "    import clrs\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/clrs/__init__.py\", line 18, in <module>\n",
      "    from clrs import models\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/clrs/models.py\", line 18, in <module>\n",
      "    from clrs._src.baselines import BaselineModel\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/clrs/_src/baselines.py\", line 25, in <module>\n",
      "    from clrs._src import decoders\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/clrs/_src/decoders.py\", line 21, in <module>\n",
      "    from clrs._src import probing\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/clrs/_src/probing.py\", line 34, in <module>\n",
      "    import tensorflow as tf\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/tensorflow/__init__.py\", line 467, in <module>\n",
      "    importlib.import_module(\"keras.src.optimizers\")\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/importlib/__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/__init__.py\", line 2, in <module>\n",
      "    from keras.api import DTypePolicy\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/api/__init__.py\", line 8, in <module>\n",
      "    from keras.api import activations\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/api/activations/__init__.py\", line 7, in <module>\n",
      "    from keras.src.activations import deserialize\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/src/__init__.py\", line 1, in <module>\n",
      "    from keras.src import activations\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/src/activations/__init__.py\", line 30, in <module>\n",
      "    from keras.src.saving import object_registration\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/src/saving/__init__.py\", line 7, in <module>\n",
      "    from keras.src.saving.saving_api import load_model\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/src/saving/saving_api.py\", line 7, in <module>\n",
      "    from keras.src.legacy.saving import legacy_h5_format\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/src/legacy/saving/legacy_h5_format.py\", line 13, in <module>\n",
      "    from keras.src.legacy.saving import saving_utils\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/src/legacy/saving/saving_utils.py\", line 10, in <module>\n",
      "    from keras.src import models\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/src/models/__init__.py\", line 1, in <module>\n",
      "    from keras.src.models.functional import Functional\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/src/models/functional.py\", line 16, in <module>\n",
      "    from keras.src.models.model import Model\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/src/models/model.py\", line 12, in <module>\n",
      "    from keras.src.trainers import trainer as base_trainer\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/src/trainers/trainer.py\", line 14, in <module>\n",
      "    from keras.src.trainers.data_adapters import data_adapter_utils\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/src/trainers/data_adapters/__init__.py\", line 4, in <module>\n",
      "    from keras.src.trainers.data_adapters import array_data_adapter\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/src/trainers/data_adapters/array_data_adapter.py\", line 7, in <module>\n",
      "    from keras.src.trainers.data_adapters import array_slicing\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/src/trainers/data_adapters/array_slicing.py\", line 12, in <module>\n",
      "    import pandas\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/pandas/__init__.py\", line 49, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/pandas/core/api.py\", line 1, in <module>\n",
      "    from pandas._libs import (\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/pandas/_libs/__init__.py\", line 17, in <module>\n",
      "    import pandas._libs.pandas_datetime  # noqa: F401 # isort: skip # type: ignore[reportUnusedImport]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/numpy/core/_multiarray_umath.py\", line 44, in __getattr__\n",
      "    raise ImportError(msg)\n",
      "ImportError: \n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "\n",
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/home/falreis/Me/doutorado/clrs/clrs/examples/run.py\", line 26, in <module>\n",
      "    import clrs\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/clrs/__init__.py\", line 18, in <module>\n",
      "    from clrs import models\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/clrs/models.py\", line 18, in <module>\n",
      "    from clrs._src.baselines import BaselineModel\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/clrs/_src/baselines.py\", line 25, in <module>\n",
      "    from clrs._src import decoders\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/clrs/_src/decoders.py\", line 21, in <module>\n",
      "    from clrs._src import probing\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/clrs/_src/probing.py\", line 34, in <module>\n",
      "    import tensorflow as tf\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/tensorflow/__init__.py\", line 467, in <module>\n",
      "    importlib.import_module(\"keras.src.optimizers\")\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/importlib/__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/__init__.py\", line 2, in <module>\n",
      "    from keras.api import DTypePolicy\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/api/__init__.py\", line 8, in <module>\n",
      "    from keras.api import activations\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/api/activations/__init__.py\", line 7, in <module>\n",
      "    from keras.src.activations import deserialize\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/src/__init__.py\", line 13, in <module>\n",
      "    from keras.src import visualization\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/src/visualization/__init__.py\", line 2, in <module>\n",
      "    from keras.src.visualization import plot_image_gallery\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/src/visualization/plot_image_gallery.py\", line 13, in <module>\n",
      "    import matplotlib.pyplot as plt\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/matplotlib/__init__.py\", line 161, in <module>\n",
      "    from . import _api, _version, cbook, _docstring, rcsetup\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/matplotlib/rcsetup.py\", line 27, in <module>\n",
      "    from matplotlib.colors import Colormap, is_color_like\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/matplotlib/colors.py\", line 57, in <module>\n",
      "    from matplotlib import _api, _cm, cbook, scale\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/matplotlib/scale.py\", line 22, in <module>\n",
      "    from matplotlib.ticker import (\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/matplotlib/ticker.py\", line 143, in <module>\n",
      "    from matplotlib import transforms as mtransforms\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/matplotlib/transforms.py\", line 49, in <module>\n",
      "    from matplotlib._path import (\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/numpy/core/_multiarray_umath.py\", line 44, in __getattr__\n",
      "    raise ImportError(msg)\n",
      "ImportError: \n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "\n",
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/home/falreis/Me/doutorado/clrs/clrs/examples/run.py\", line 26, in <module>\n",
      "    import clrs\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/clrs/__init__.py\", line 18, in <module>\n",
      "    from clrs import models\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/clrs/models.py\", line 18, in <module>\n",
      "    from clrs._src.baselines import BaselineModel\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/clrs/_src/baselines.py\", line 25, in <module>\n",
      "    from clrs._src import decoders\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/clrs/_src/decoders.py\", line 21, in <module>\n",
      "    from clrs._src import probing\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/clrs/_src/probing.py\", line 34, in <module>\n",
      "    import tensorflow as tf\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/tensorflow/__init__.py\", line 467, in <module>\n",
      "    importlib.import_module(\"keras.src.optimizers\")\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/importlib/__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/__init__.py\", line 2, in <module>\n",
      "    from keras.api import DTypePolicy\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/api/__init__.py\", line 34, in <module>\n",
      "    from keras.api import visualization\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/api/visualization/__init__.py\", line 11, in <module>\n",
      "    from keras.src.visualization.plot_bounding_box_gallery import (\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/keras/src/visualization/plot_bounding_box_gallery.py\", line 12, in <module>\n",
      "    from matplotlib import patches  # For legend patches\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/matplotlib/__init__.py\", line 161, in <module>\n",
      "    from . import _api, _version, cbook, _docstring, rcsetup\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/matplotlib/rcsetup.py\", line 27, in <module>\n",
      "    from matplotlib.colors import Colormap, is_color_like\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/matplotlib/colors.py\", line 57, in <module>\n",
      "    from matplotlib import _api, _cm, cbook, scale\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/matplotlib/scale.py\", line 22, in <module>\n",
      "    from matplotlib.ticker import (\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/matplotlib/ticker.py\", line 143, in <module>\n",
      "    from matplotlib import transforms as mtransforms\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/matplotlib/transforms.py\", line 49, in <module>\n",
      "    from matplotlib._path import (\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/numpy/core/_multiarray_umath.py\", line 44, in __getattr__\n",
      "    raise ImportError(msg)\n",
      "ImportError: \n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "\n",
      "INFO:2025-01-04 16:48:34,884:jax._src.xla_bridge:927: Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'\n",
      "I0104 16:48:34.884977 137046390683136 xla_bridge.py:927] Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'\n",
      "INFO:2025-01-04 16:48:34,885:jax._src.xla_bridge:927: Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory\n",
      "I0104 16:48:34.885972 137046390683136 xla_bridge.py:927] Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/falreis/Me/doutorado/clrs/clrs/examples/run.py\", line 586, in <module>\n",
      "    app.run(main)\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/absl/app.py\", line 308, in run\n",
      "    _run_main(main, args)\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/absl/app.py\", line 254, in _run_main\n",
      "    sys.exit(main(argv))\n",
      "             ^^^^^^^^^^\n",
      "  File \"/home/falreis/Me/doutorado/clrs/clrs/examples/run.py\", line 418, in main\n",
      "    rng_key = jax.random.PRNGKey(rng.randint(2**32))\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/jax/_src/random.py\", line 246, in PRNGKey\n",
      "    return _return_prng_keys(True, _key('PRNGKey', seed, impl))\n",
      "                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/jax/_src/random.py\", line 198, in _key\n",
      "    return prng.random_seed(seed, impl=impl)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/jax/_src/prng.py\", line 541, in random_seed\n",
      "    return random_seed_p.bind(seeds_arr, impl=impl)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/jax/_src/core.py\", line 463, in bind\n",
      "    return self.bind_with_trace(prev_trace, args, params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/jax/_src/core.py\", line 468, in bind_with_trace\n",
      "    return trace.process_primitive(self, args, params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/jax/_src/core.py\", line 941, in process_primitive\n",
      "    return primitive.impl(*args, **params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/jax/_src/prng.py\", line 553, in random_seed_impl\n",
      "    base_arr = random_seed_impl_base(seeds, impl=impl)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/jax/_src/prng.py\", line 558, in random_seed_impl_base\n",
      "    return seed(seeds)\n",
      "           ^^^^^^^^^^^\n",
      "  File \"/home/falreis/anaconda3/lib/python3.12/site-packages/jax/_src/prng.py\", line 774, in threefry_seed\n",
      "    return _threefry_seed(seed)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "jaxlib.xla_extension.XlaRuntimeError: INTERNAL: ptxas exited with non-zero error code 139, output: ptxas /tmp/tempfile-falreis-AB350M-DS3H-V2-e0ca28bd1d40a982-7345-62ae6ae4735b0, line 5; fatal   : Unsupported .version 8.3; current version is '8.0'\n",
      "\n",
      "--------------------\n",
      "For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.\n"
     ]
    }
   ],
   "source": [
    "!python3 examples/run.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3ec65c6c-039d-4abe-9020-6a98ee79f29b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
